version: "3.8"

services:
  cassandra:
    image: cassandra:5.0
    container_name: fact_checker_cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=fact_checker_cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - HEAP_NEWSIZE=200M
      - MAX_HEAP_SIZE=3G
      - CASSANDRA_HEAP_SIZE=3G
      - CASSANDRA_CONCURRENT_WRITES=32
      - CASSANDRA_CONCURRENT_READS=32
      - CASSANDRA_CONCURRENT_COUNTER_WRITES=32
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u",
          "cassandra",
          "-p",
          "cassandra",
          "-e",
          "describe keyspaces",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  cassandra_data:
